services:

  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      - VERSION:"win11"
      - LANGUAGE:"Spanish"
      - REGION:"es-ES"
      - KEYBOARD:"es-ES"
      - DISK_SIZE:"64G"
      - RAM_SIZE:"8G"
      - CPU_CORES:"4"
      - USERNAME:"admin"
      - PASSWORD:"p4ssw0rd"
    volumes:
      - /var/win:/storage 
      - /home/user/example:/shared 
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m

