services:

  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      - VERSION: "11"
      - LANGUAGE:"Spanish"   # opcional
      - REGION:"es-ES"       # opcional
      - KEYBOARD:"es-ES"     # opcional
      - DISK_SIZE:"64G"      # opcional
      - RAM_SIZE:"8G"        # opcional
      - CPU_CORES:"4"        # opcional 
      - USERNAME:"admin"     # opcional
      - PASSWORD:"p4ssw0rd"  # opcional
    volumes:
      - /var/win:/storage            # opcional
      - /home/user/example:/shared   # opcional
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m

